### ISSUE TITLE
Not compatible with Magento2 alpha 106

### ISSUE THREAD

**Issue by ihor-sviziev** [tzyganu/m2-sample-data#2]
Tried to install this sample data with aplha 106 and after installation got report:

```
a:4:{i:0;s:73:"Looks like database is outdated. Please, use setup tool to perform update";i:1;s:2586:"#0 [internal 
function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontCont
roller\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 /lamp/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(81): call_user_func_array(Array, Arra
y)
#2 /lamp/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(76): Magento\Framework\Interception\C
hain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor)
, Array, 'front-controlle...')
#3 /lamp/magento2/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(79): Magento\Framework\Int
erception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#4 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Fr
amework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#5 /lamp/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(81): call_user_func_array(Array, Arra
y)
#6 /lamp/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(88): Magento\Framework\Inter
ception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Int
erceptor), Array, 'front-controlle...')
#7 /lamp/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(90): Magento\Framework\App
\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}(Object(Magento\Framework\App\Request\
Http))
#8 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Fr
amework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /lamp/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(93): call_user_func_array(Ar
ray, Array)
#10 /lamp/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(115): Magento\Framework\App
\FrontController\Interceptor->___call('dispatch', Array, Array)
#11 /lamp/magento2/lib/internal/Magento/Framework/App/Http.php(133): Magento\Framework\App\FrontController\Intercep
tor->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /lamp/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#13 /lamp/magento2/index.php(43): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#14 {main}";s:3:"url";s:10:"/magento2/";s:11:"script_name";s:19:"/magento2/index.php";}
```

**Comment by tzyganu** [comment]
No, it is not compatible with alpha106. If you take a look at the readme file you will see that it was last tested on alpha 105. I will make it compatible with 106 when i get some spare time.

**Comment by tzyganu** [comment]
The new version is compatible with alpha 106.

**Comment by ihor-sviziev** [comment]
@tzyganu thx
